<?php declare(strict_types = 1);

// phpcs:disable SlevomatCodingStandard.Files.LineLength.LineTooLong
return [
	"components > callbacks > callback > expression > get > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > get > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > get > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > get > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > get > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > get > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > get > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > get > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > get > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > put > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > put > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > put > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > put > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > put > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > put > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > put > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > put > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > put > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > post > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > post > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > post > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > post > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > post > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > post > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > post > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > post > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > post > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > delete > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > delete > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > delete > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > delete > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > delete > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > delete > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > delete > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > delete > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > delete > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > options > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > options > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > options > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > options > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > options > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > options > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > options > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > options > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > options > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > head > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > head > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > head > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > head > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > head > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > head > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > head > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > head > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > head > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > patch > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > patch > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > patch > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > patch > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > patch > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > patch > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > patch > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > patch > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > patch > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > trace > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > trace > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > trace > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > trace > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > trace > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > trace > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > trace > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > trace > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > trace > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > callbacks > callback > expression > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > headers > header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > headers > header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > get > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > get > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > get > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > get > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > get > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > get > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > get > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > get > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > get > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > put > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > put > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > put > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > put > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > put > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > put > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > put > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > put > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > put > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > post > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > post > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > post > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > post > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > post > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > post > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > post > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > post > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > post > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > delete > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > delete > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > delete > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > delete > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > delete > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > delete > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > delete > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > delete > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > delete > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > options > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > options > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > options > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > options > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > options > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > options > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > options > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > options > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > options > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > head > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > head > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > head > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > head > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > head > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > head > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > head > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > head > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > head > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > patch > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > patch > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > patch > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > patch > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > patch > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > patch > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > patch > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > patch > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > patch > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > trace > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > trace > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > trace > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > trace > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > trace > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > trace > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > trace > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > trace > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > trace > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > callbacks > callback > expression > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > get > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > put > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > put > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > put > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > put > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > put > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > put > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > put > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > put > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > put > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > post > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > post > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > post > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > post > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > post > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > post > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > post > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > post > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > post > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > delete > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > delete > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > delete > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > delete > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > delete > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > delete > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > delete > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > delete > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > delete > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > options > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > options > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > options > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > options > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > options > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > options > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > options > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > options > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > options > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > head > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > head > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > head > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > head > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > head > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > head > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > head > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > head > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > head > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > patch > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > patch > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > patch > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > patch > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > patch > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > patch > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > patch > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > patch > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > patch > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > trace > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > trace > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > trace > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > trace > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > trace > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > trace > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > trace > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > trace > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > trace > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > pathItems > path > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > parameters > parameter: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > requestBodies > body > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > requestBodies > body > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > requestBodies > body > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > responses > response > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > responses > response > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > responses > response > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > responses > response > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"components > responses > response > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > get > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > get > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > get > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > get > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > get > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > get > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > get > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > get > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > get > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > put > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > put > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > put > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > put > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > put > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > put > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > put > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > put > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > put > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > post > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > post > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > post > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > post > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > post > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > post > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > post > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > post > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > post > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > delete > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > delete > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > delete > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > delete > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > delete > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > delete > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > delete > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > delete > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > delete > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > options > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > options > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > options > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > options > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > options > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > options > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > options > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > options > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > options > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > head > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > head > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > head > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > head > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > head > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > head > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > head > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > head > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > head > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > patch > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > patch > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > patch > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > patch > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > patch > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > patch > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > patch > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > patch > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > patch > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > trace > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > trace > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > trace > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > trace > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > trace > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > trace > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > trace > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > trace > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > trace > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > callbacks > callback > expression > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > get > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > put > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > put > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > put > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > put > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > put > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > put > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > put > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > put > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > put > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > post > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > post > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > post > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > post > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > post > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > post > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > post > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > post > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > post > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > delete > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > delete > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > delete > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > delete > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > delete > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > delete > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > delete > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > delete > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > delete > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > options > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > options > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > options > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > options > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > options > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > options > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > options > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > options > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > options > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > head > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > head > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > head > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > head > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > head > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > head > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > head > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > head > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > head > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > patch > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > patch > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > patch > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > patch > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > patch > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > patch > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > patch > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > patch > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > patch > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > trace > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > trace > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > trace > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > trace > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > trace > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > trace > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > trace > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > trace > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > trace > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"paths > / > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > get > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > get > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > get > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > get > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > get > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > get > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > get > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > get > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > get > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > put > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > put > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > put > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > put > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > put > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > put > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > put > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > put > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > put > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > post > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > post > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > post > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > post > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > post > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > post > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > post > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > post > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > post > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > delete > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > delete > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > delete > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > delete > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > delete > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > delete > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > delete > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > delete > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > delete > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > options > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > options > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > options > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > options > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > options > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > options > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > options > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > options > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > options > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > head > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > head > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > head > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > head > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > head > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > head > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > head > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > head > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > head > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > patch > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > patch > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > patch > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > patch > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > patch > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > patch > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > patch > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > patch > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > patch > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > trace > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > trace > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > trace > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > trace > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > trace > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > trace > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > trace > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > trace > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > trace > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > callbacks > callback > expression > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > get > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > put > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > put > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > put > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > put > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > put > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > put > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > put > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > put > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > put > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > post > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > post > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > post > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > post > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > post > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > post > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > post > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > post > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > post > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > delete > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > delete > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > delete > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > delete > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > delete > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > delete > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > delete > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > delete > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > delete > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > options > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > options > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > options > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > options > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > options > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > options > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > options > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > options > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > options > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > head > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > head > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > head > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > head > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > head > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > head > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > head > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > head > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > head > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > patch > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > patch > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > patch > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > patch > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > patch > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > patch > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > patch > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > patch > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > patch > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > trace > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > trace > requestBody > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > trace > requestBody > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > trace > requestBody > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > trace > responses > 200 > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > trace > responses > 200 > content > application/json > encoding > a > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > trace > responses > 200 > content > application/json > encoding > a > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > trace > responses > 200 > headers > Header: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > trace > responses > 200 > headers > Header > content > application/json: Both 'example' and 'examples' are defined, only one is allowed.",
	"webhooks > / > parameters > 0: Both 'example' and 'examples' are defined, only one is allowed.",
];
